### PR TITLE
[RFC] Convert Path::Router to Moo

### PR DESCRIPTION
**Pull request by felliott**
Hello!

This branch converts Path::Router to use Moo in place of Moose.  The Moose types have been replaced with Type::Tiny and Types::Standard.  Since Moo doesn't have it's own version of MooseX::Clone, I've taken out the ::Clone traits and added a hand-rolled sub clone() to Path::Router::Route.  Is this something you are interested in?  If so, please let me know if you'd like me to change, refactor, or rebase anything.  Thank you and have a great day!

Cheers,
Fitz Elliott

### CODE REVIEW

**Comment by genehack** [comment]
FWIW, a version of Moo without the strictures issue has been out for a while. @stevan -- thoughts on applying this?

**Comment by stevan** [comment]
Actually @neilbowers has Path::Router for the PR challange, maybe he would like to review this patch ;)

**Comment by neilbowers** [comment]
@stevan yeah, ok. I'm catching up on email after a weekend away. Will look at either tomorrow night, or more likely Tuesday night.

**Comment by stevan** [comment]
@neilbowers sounds good, thanks for taking a look.

FWIW, I reviewed it again and it all looks good to me.

**Comment by neilbowers** [comment]
First thoughts are on what versions of modules to require:

* should specify the version on Moo (noticed @stevan commented). Looking at [the Changes file](https://metacpan.org/changes/distribution/Moo), you might want to specify 2.000001
* namespace::clean should maybe be 0.23 as a minimum? ([Changes file](https://metacpan.org/changes/distribution/namespace-clean))
* Clone::PP 1.04 ([Changes](https://metacpan.org/changes/distribution/Clone-PP)). Really you want to depend on 1.03, since it specifies the prereqs and fixes warnings, but I muffed up one prereq, which I then fixed in 1.04 :-)
* I don't have any experience with Type::Tiny, but maybe specify version 1.000005? If you're going to require it, might as well specify a version that pulls in lots of fixes. There hasn't been any fixes for a while since that release, but maybe that's down to Toby going quiet, rather than stability? (I've no idea either way).
* Eval::Closure has 0.06 specified, but from the [Changes file](https://metacpan.org/changes/distribution/Eval-Closure), there are some fixes in 0.12 and 0.13 that look like they'll be required for 5.22? So bump the version to 0.13? 

Also, instead of explicitly putting the versions in `dist.ini`, you could specify them when use'ing the module, and use `[AutoPrereqs]` in `dist.ini`. That way you have the required version documented in the code.

**Comment by neilbowers** [comment]
BTW, if you want to merge this, I'll do another PR to add the versions, and the other small things I suggested, @stevan :-)

**Comment by stevan** [comment]
Sounds good to me :)

**Comment by neilbowers** [comment]
@stevan how you wanna do this? If you merge @felliott's PR, I'll then fork your repo and send a PR on top of that. Or ... ?

**Comment by stevan** [comment]
@neilbowers, I dub thee, collaborator!

**Comment by genehack** [comment]
i love it when a plan comes together.

**Comment by neilbowers** [comment]
@stevan no, no! you bugger. I'm supposed to be *doing* a PR on this, not merging someone else's :-p

Er, I mean, thanks. Yeah, thanks.

**Comment by neilbowers** [comment]
@felliott thanks!

I'm going to add versions to various modules being used, and some other minor changes.

Then I'll do a developer release, and if that's good (after a week), I'll ask @stevan to release.

**Comment by felliott** [comment]
> On Jul 2, 2015, at 4:39 PM, Neil Bowers <notifications@github.com> wrote:
> 
> @felliott thanks!
> 
> I'm going to add versions to various modules being used, and some other minor changes.
> 
> Then I'll do a developer release, and if that's good (after a week), I'll ask @stevan to release.

Sounds good!  Thanks @neilbowers, @stevan, and @genehack!

Cheers,
Fitz

**Comment by timbunce** [comment]
Seconded. Many thanks to all.

/me hopes to get back to WAPID work soonish...

**Comment by neilb** [comment]
@felliott this has finally been released to CPAN (v0.15) -- thanks again for doing this, and sorry for the delay in releasing it to CPAN.

**Pull request merged**
